Xray: added xray_get_rcv_event_sock. return sock_fd that can be sent …
xrayio/libxray pull request #21
Opened 2018-07-26 13:14 UTC by imenashe-dn

…to poll/select

2018-07-28 17:28 UTC, grishaf requested changes
please add tests in order this functionalliy will not be broken. run `make test` or `make test-in-docker` to run the tests

2018-07-28 17:28 UTC, grishaf commented on src/xray.cpp
> +xray_get_rcv_event_sock(int *res)
I want to add support for XrayServer(cluster). XrayNode will open two sockets - one local uds (as today) and one to XrayServer. can you make this function api:
`int xray_get_rcv_event_sock(int *rx_sockets, int *n_sockets)`

2018-07-29 04:10 UTC, kfir-drivenets commented
what about time related triggers? seems to me like waiting only on the file descriptors has the potential to break the rate computation feature

2018-07-29 05:33 UTC, grishaf commented
@kfir-drivenets you are right, with list it can be fixed easily. BTW, what is better list or mask?

2018-11-07 09:31 UTC, closed without merging

2018-11-07 14:16 UTC, kfir-drivenets commented
I think that its similar to select vs epoll.
Select uses a mask with 1024 bits.
Epoll uses a list.
Epoll is much more scalable for large number of file descriptors.
I wouldn't go with the mask approach.